### ISSUE TITLE
Error message: an error occurred, no other context

### ISSUE THREAD

**Issue by johnabs** [scintill/DuOTP-android#6]
Hi there!

I'm trying to get this to work on my new de-googled phone (and I tried it on my old googled one too). I installed the apk from Fdroid, got the link from my employer, and when I tried to open the link, it allowed me to select duotp instead of duo mobile. I selected DuOTP, but it failed with "an error occurred". 

For reference, I tried with Aegis first, then Google Authenticator, but no dice on either one. If you wouldn't mind, could you provide some guidance here? I'd really love to get this working :)

**Comment by mariobrostech** [comment]
Hi,

I'm experiencing this error message too. Did you end up getting it to work, or did you close the issue due to inactivity?

Thanks in advance!

**Comment by mariobrostech** [comment]
Hi @johnabs,

I'm experiencing this error message too. Did you end up getting it to work, or did you close the issue due to inactivity?

Thanks in advance!

**Comment by adv4ncr** [comment]
Same issue here. I would also be interested in the solution

**Comment by TheNewsYorkTime** [comment]
I also have this issue
